# Generated by Django 4.2.7 on 2025-12-23 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_type', models.CharField(max_length=50)),
                ('data_json', models.JSONField()),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('division_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('policy_area', models.CharField(blank=True, max_length=100, null=True)),
                ('aye_count', models.IntegerField(default=0)),
                ('no_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(choices=[('1', 'Employment and earnings'), ('2', 'Donations and other support'), ('3', 'Gifts, benefits and hospitality'), ('4', 'Visits outside the UK'), ('5', 'Land and property'), ('6', 'Shareholdings'), ('7', 'Miscellaneous')], max_length=2)),
                ('summary', models.TextField()),
                ('registered_date', models.DateField(blank=True, null=True)),
                ('ai_sector', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('ai_payer', models.CharField(blank=True, max_length=200, null=True)),
                ('ai_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('last_ai_processed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-registered_date'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('party', models.CharField(max_length=100)),
                ('constituency', models.CharField(max_length=200)),
                ('portrait_url', models.URLField(blank=True, null=True)),
                ('current_status', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('AYE', 'Aye'), ('NO', 'No'), ('ABSTAIN', 'Abstain'), ('ABSENT', 'Absent')], max_length=10)),
                ('conflict_score', models.FloatField(default=0.0)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='parliament.division')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='parliament.member')),
            ],
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['constituency'], name='parliament__constit_5f1e7d_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['party'], name='parliament__party_97f738_idx'),
        ),
        migrations.AddField(
            model_name='interest',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='parliament.member'),
        ),
        migrations.AddIndex(
            model_name='division',
            index=models.Index(fields=['date'], name='parliament__date_72b90a_idx'),
        ),
        migrations.AddIndex(
            model_name='division',
            index=models.Index(fields=['policy_area'], name='parliament__policy__1e3792_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['member', 'division'], name='parliament__member__d141fa_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['conflict_score'], name='parliament__conflic_dcf350_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('member', 'division')},
        ),
        migrations.AddIndex(
            model_name='interest',
            index=models.Index(fields=['member', 'category_code'], name='parliament__member__9b2032_idx'),
        ),
        migrations.AddIndex(
            model_name='interest',
            index=models.Index(fields=['ai_sector'], name='parliament__ai_sect_b1e7b1_idx'),
        ),
    ]
