# Generated by Django 4.2.7 on 2025-12-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
