# Generated by Django 4.2.7 on 2025-12-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0002_interest_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='summary',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
