# Generated by Django 4.2.7 on 2025-12-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0003_alter_interest_summary'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='interest',
            name='parliament__member__9b2032_idx',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='category_code',
        ),
        migrations.AddField(
            model_name='interest',
            name='interest_type',
            field=models.CharField(choices=[('shareholding', 'Shareholding'), ('consultancy', 'Paid Employment / Consultancy'), ('speech', 'Paid Speech / Appearance'), ('gift', 'Gifts / Hospitality / Travel'), ('trusteeship', 'Unpaid Directorship / Trusteeship'), ('donation', 'Donation / Grant / Sponsorship'), ('property', 'Land / Property / Real Estate'), ('other', 'Other / Miscellaneous')], default='other', max_length=30),
        ),
        migrations.AddIndex(
            model_name='interest',
            index=models.Index(fields=['member'], name='parliament__member__905051_idx'),
        ),
    ]
