# Generated by Django 4.2.7 on 2025-12-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0004_remove_interest_parliament__member__9b2032_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='raw_summary',
            field=models.TextField(default='other'),
        ),
    ]
