# Generated by Django 4.2.7 on 2025-12-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0005_interest_raw_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='parliament_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
