# Generated by Django 4.2.7 on 2025-12-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0006_member_last_synced_at_member_parliament_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
