# Generated by Django 4.2.7 on 2025-12-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0007_alter_interest_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='interest',
            name='raw_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='division',
            name='policy_tags',
            field=models.ManyToManyField(blank=True, to='parliament.policytag'),
        ),
    ]
