# Generated by Django 4.2.7 on 2026-01-04 19:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0009_remove_policy_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='division',
            name='policy_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.RemoveField(
            model_name='division',
            name='policy_tags',
        ),
        migrations.AddField(
            model_name='division',
            name='policy_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='AI-determined policy sectors', size=None),
        ),
    ]
