# Generated by Django 4.2.7 on 2026-01-04 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0010_division_description_division_policy_confidence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='division',
            old_name='division_id',
            new_name='id',
        ),
    ]
